app/build.gradle
app/src/androidTest/java/in/ac/bits_pilani/goa/ard/activities/MainActivityTest.java
app/src/main/java/in/ac/bits_pilani/goa/ard/activities/MainActivity.java
app/src/main/java/in/ac/bits_pilani/goa/ard/fragments/ChatFragment.java
app/src/main/java/in/ac/bits_pilani/goa/ard/fragments/FaqFragment.java
app/src/main/java/in/ac/bits_pilani/goa/ard/fragments/HomeFragment.java
app/src/main/java/in/ac/bits_pilani/goa/ard/interfaces/ChatFragmentListener.java
app/src/main/java/in/ac/bits_pilani/goa/ard/interfaces/FaqFragmentListener.java
app/src/main/java/in/ac/bits_pilani/goa/ard/interfaces/HomeFragmentListener.java
app/src/main/java/in/ac/bits_pilani/goa/ard/utils/AHC.java
app/src/main/res/drawable/ic_chat_24dp.xml
app/src/main/res/drawable/ic_faq_24dp.xml
app/src/main/res/drawable/ic_home_24dp.xml
app/src/main/res/drawable/icon_csl_bottom_nav.xml
app/src/main/res/drawable/text_csl_bottom_nav.xml
app/src/main/res/layout/app_bar_main.xml
app/src/main/res/layout/content_main.xml
app/src/main/res/layout/fragment_chat.xml
app/src/main/res/layout/fragment_faq.xml
app/src/main/res/layout/fragment_home.xml
app/src/main/res/menu/menu_activity_main_bottom_nav.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

Issue #64: Add Bottom Navigation View

---

app/build.gradle
build.gradle

Issue #92 
Updating Libraries
1. build tools -> `26.0.0`
2. checkstyle -> `7.8.1`
3. firebase -> `11.0.0`
4. support library -> `25.4.0`
5. realm -> `3.3.1`

Updating Libraries

---

.travis.yml
app/src/androidTest/java/in/ac/bits_pilani/goa/ard/general/ApplicationTest.java

Issue #96 
First commit is a deliberate faling build. We should get logcat for it.

Issue #96: Added logcat output for failing build

---

config/checkstyle/checkstyle.xml
config/checkstyle/suppressions.xml

Issue #102 
Also removed MissingCtor suppression.

Issue #102: Removed MissingCtor from CS

---

.codecov.yml
.travis.yml
app/build.gradle
app/src/androidTest/java/in/ac/bits_pilani/goa/ard/activities/MainActivityTest.java
app/src/main/java/in/ac/bits_pilani/goa/ard/activities/MainActivity.java
app/src/main/java/in/ac/bits_pilani/goa/ard/adapters/ViewPagerAdapter.java
app/src/main/java/in/ac/bits_pilani/goa/ard/fragments/FaqFragment.java
app/src/main/java/in/ac/bits_pilani/goa/ard/fragments/FaqGeneralFragment.java
app/src/main/res/layout/fragment_faq.xml
app/src/main/res/layout/fragment_faq_content.xml
app/src/main/res/layout/fragment_faq_general.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml
app/src/test/java/in/ac/bits_pilani/goa/ard/adapters/ViewPagerAdapterTest.java
app/src/test/java/in/ac/bits_pilani/goa/ard/fragments/FaqFragmentTest.java

Issue #78: Add General FAQ subsection

---

README.md

Issue #3 
Updated Version eye link and license issues

Issue #3: Update VersionEye link

---

app/build.gradle
app/src/androidTest/java/in/ac/bits_pilani/goa/ard/utils/BrowserTest.java
app/src/main/java/in/ac/bits_pilani/goa/ard/utils/AHC.java
app/src/main/java/in/ac/bits_pilani/goa/ard/utils/Browser.java
app/src/main/java/in/ac/bits_pilani/goa/ard/utils/BrowserUtil.java
app/src/main/res/drawable/ic_close_24dp.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/styles.xml
app/src/test/java/in/ac/bits_pilani/goa/ard/utils/BrowserUtilTest.java

Issue #89 
Created utility class `Browser` to provide functionality of opening url in custom tab.

Issue #89: Added support for custom tabs

---

README.md

Issue #116: Update travis ci badge and links

---

app/build.gradle

Issue #118: Move checkstyle tasks up

---

app/proguard-rules.pro

Issue #126 
https://github.com/bumptech/glide#proguard
Have uncommented the first 2lines as we are not implementing any glide modules

Issue #126: Add Glide proguard settings

---

app/build.gradle

Issue #123: Bump Mockito to 2.8.47

---

.gitignore

Issue #129: added .idea/codeStyleSettings.xml to .gitignore [skip ci]

---

app/build.gradle

Issue #133: Delete temp coverage report

---

app/src/androidTest/java/com/macbitsgoa/ard/activities/SettingsActivityTest.java
app/src/main/AndroidManifest.xml
app/src/main/java/com/macbitsgoa/ard/activities/MainActivity.java
app/src/main/java/com/macbitsgoa/ard/activities/SettingsActivity.java
app/src/main/java/com/macbitsgoa/ard/fragments/SettingsFragment.java
app/src/main/res/layout/activity_settings.xml
app/src/main/res/layout/content_settings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences.xml

Issue #42: Add empty Settings activity

---

.ci/travis/apkHost.sh
.travis.yml

Issue #3: Add script to post apk for builds to server

---

.travis.yml
app/build.gradle
app/google-services.json
app/src/androidTest/java/com/macbitsgoa/ard/activities/AuthActivityTest.java
app/src/androidTest/java/com/macbitsgoa/ard/activities/MainActivityTest.java
app/src/androidTest/java/com/macbitsgoa/ard/fragments/HomeFragmentTest.java
app/src/androidTest/java/com/macbitsgoa/ard/utils/BrowserTest.java
app/src/main/AndroidManifest.xml
app/src/main/java/com/macbitsgoa/ard/activities/AuthActivity.java
app/src/main/java/com/macbitsgoa/ard/activities/BaseActivity.java
app/src/main/java/com/macbitsgoa/ard/activities/MainActivity.java
app/src/main/java/com/macbitsgoa/ard/helpers/AuthHelperForGoogle.java
app/src/main/java/com/macbitsgoa/ard/keys/AuthActivityKeys.java
app/src/main/java/com/macbitsgoa/ard/keys/UserItemKeys.java
app/src/main/java/com/macbitsgoa/ard/models/AnnItem.java
app/src/main/java/com/macbitsgoa/ard/models/UserItem.java
app/src/main/java/com/macbitsgoa/ard/utils/AHC.java
app/src/main/res/drawable/google_g.xml
app/src/main/res/layout/activity_auth.xml
app/src/main/res/layout/content_auth.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml
app/src/test/java/com/macbitsgoa/ard/helpers/AuthHelperGoogleTest.java
app/src/test/java/com/macbitsgoa/ard/models/UserItemTest.java

Issue #43: Add Google sign in

---

.ci/travis/check_pr.sh
.travis.yml

Issue #32: Fix PR format checking

---

.ci/travis/pastebinit.sh
.ci/travis/startEmulator.sh
.travis.yml

Issue #105: Add API 22 to travis tests

---

app/src/androidTest/java/com/macbitsgoa/ard/THC.java
app/src/androidTest/java/com/macbitsgoa/ard/activities/AuthActivityTest.java
app/src/androidTest/java/com/macbitsgoa/ard/activities/MainActivityTest.java
app/src/androidTest/java/com/macbitsgoa/ard/fragments/HomeAnnFragmentTest.java

Issue #142: Add THC for useful methods in testing

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
.github/git-workflow.md
README.md

Issue #147 
1. Added git workflow guide.
2. Modified `README.md`, `.github/CONTRIBUTING.md`, `.github/PULL_REQUEST_TEMPLATE.md` to solve #115

Issue #147: Added git workflow guide

---

.ci/travis/apkHost.sh
.ci/travis/check_pr.sh
.ci/travis/pastebinit.sh
.ci/travis/startEmulator.sh

Issue #146: Add set -e command to scripts to allow failure

---

.travis.yml
app/build.gradle
app/proguard-rules.pro
app/src/androidTest/java/com/macbitsgoa/ard/activities/AuthActivityTest.java
build.gradle
gradle/wrapper/gradle-wrapper.properties

Bump gradle dependencies versions
2 unit tests have been ignored to prevent local build failure..Will review them later

Bump gradle dependencies and add Roboelectric

---

app/src/androidTest/java/com/macbitsgoa/ard/fragments/HomeFragmentTest.java
app/src/main/AndroidManifest.xml
app/src/main/java/com/macbitsgoa/ard/activities/PostDetailsActivity.java
app/src/main/java/com/macbitsgoa/ard/fragments/HomeFragment.java
app/src/main/java/com/macbitsgoa/ard/interfaces/OnItemClickListener.java
app/src/main/java/com/macbitsgoa/ard/interfaces/RecyclerItemClickListener.java
app/src/main/java/com/macbitsgoa/ard/keys/PostKeys.java
app/src/main/res/drawable/ic_share.xml
app/src/main/res/drawable/ic_smiley.xml
app/src/main/res/layout/activity_post_details.xml
app/src/main/res/layout/content_post_details.xml
app/src/main/res/layout/frame_comment.xml
app/src/main/res/layout/frame_share.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml
config/checkstyle/checkstyle.xml
config/checkstyle/suppressions.xml

Issue #143: Add basic structure for post details

---

app/src/main/java/com/macbitsgoa/ard/activities/MainActivity.java
app/src/main/java/com/macbitsgoa/ard/fragments/ForumFragment.java
app/src/main/java/com/macbitsgoa/ard/fragments/forum/GeneralFragment.java
build.gradle

The adapter probably gets unset from recycler view after `onStop()`

fixes #184

---

app/src/main/java/com/macbitsgoa/ard/fragments/HomeFragment.java
app/src/main/res/layout/fragment_home.xml

fixed issue #181

---

app/src/main/java/com/macbitsgoa/ard/activities/MainActivity.java

#167 
Fragments will be remembered on orientation change.

Fixed issue #167

---

app/src/main/java/com/macbitsgoa/ard/activities/MainActivity.java

Issue #189 
Implemented fragment recency list.
We keep track of most recent section launches. On back press, we launch the previous section and delete current one from history. When history is empty we launch home if it's not the current section else exit.

Implemented fragment recency list

---

app/src/main/java/com/macbitsgoa/ard/activities/MainActivity.java
app/src/main/java/com/macbitsgoa/ard/fragments/DetailsFragment.java

Added check for Google Play Services Availability
